### ISSUE TITLE
Crash on Startup with ASP.NET Core 2.1.x packages

### ISSUE THREAD

**Issue by billbogaiv** [billbogaiv/hybrid-model-binding#11]
When the base library packages use version `2.1.x`, the following error is generated during sample startup. **It occurs just by the library referencing the `Microsoft.AspNetCore.Mvc.Core` package**. For now, version `2.0.4` seems to be the highest version to not cause the error.

```
System.MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker..ctor(System.Diagnostics.DiagnosticSource, Microsoft.Extensions.Logging.ILogger, Microsoft.AspNetCore.Mvc.ActionContext, Microsoft.AspNetCore.Mvc.Filters.IFilterMetadata[], System.Collections.Generic.IList`1<Microsoft.AspNetCore.Mvc.ModelBinding.IValueProviderFactory>)'.
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvokerProvider.CreateActionInvoker(ActionContext actionContext, PageActionInvokerCacheEntry cacheEntry, IFilterMetadata[] filters)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvokerProvider.OnProvidersExecuting(ActionInvokerProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionInvokerFactory.CreateInvoker(ActionContext actionContext)
   at Microsoft.AspNetCore.Mvc.Internal.MvcAttributeRouteHandler.<>c__DisplayClass12_0.<RouteAsync>b__0(HttpContext c)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

**Comment by billbogaiv** [comment]
This issue didn't take too long to identify–a breaking change in the `Microsoft.AspNetCore.Mvc.Core` package: https://github.com/aspnet/Mvc/pull/7526/files#diff-18151f7c775126182caaa35da19d1b1dR43. The `ResourceInvoker` constructor was changed and the runtime in the sample app. (ASP.NET Core version 2.0.4) was trying to invoke a method that no longer matched the expected signature. I guess even though the sample app. and library used two different versions, the higher-versioned one "wins" during runtime.?

I will be submitting updates to both library and sample to `2.1.1` shortly. Package will be: https://www.nuget.org/packages/HybridModelBinding/0.8.0
